// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("interface_tap_bpf")
            .map("perf_map", false)
            .map("interfac.rodata", false)
            .prog("read_from_interface");
        builder.build()
    }
    pub struct OpenInterfaceTapMaps<'obj> {
        pub perf_map: libbpf_rs::OpenMapMut<'obj>,
        pub rodata: libbpf_rs::OpenMapMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenInterfaceTapMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut perf_map = None;
            let mut rodata = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "perf_map" => perf_map = Some(map),
                    "interfac.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                perf_map: perf_map.expect("map `perf_map` not present"),
                rodata: rodata.expect("map `rodata` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct InterfaceTapMaps<'obj> {
        pub perf_map: libbpf_rs::MapMut<'obj>,
        pub rodata: libbpf_rs::MapMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> InterfaceTapMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut perf_map = None;
            let mut rodata = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "perf_map" => perf_map = Some(map),
                    "interfac.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                perf_map: perf_map.expect("map `perf_map` not present"),
                rodata: rodata.expect("map `rodata` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenInterfaceTapProgs<'obj> {
        pub read_from_interface: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenInterfaceTapProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut read_from_interface = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "read_from_interface" => read_from_interface = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                read_from_interface: read_from_interface
                    .expect("prog `read_from_interface` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct InterfaceTapProgs<'obj> {
        pub read_from_interface: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> InterfaceTapProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenInterfaceTapProgs<'obj>) -> Self {
            Self {
                read_from_interface: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.read_from_interface.as_libbpf_object().as_mut(),
                    )
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct InterfaceTapSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> InterfaceTapSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenInterfaceTapSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenInterfaceTapSkel {
                maps: unsafe { OpenInterfaceTapMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenInterfaceTapProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for InterfaceTapSkelBuilder {
        type Output = OpenInterfaceTapSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenInterfaceTapSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenInterfaceTapSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_1 {
            pub r#type: *mut [i32; 17],
            pub max_entries: *mut [i32; 16777216],
            pub key: *mut i32,
            pub value: *mut u32,
        }
        impl Default for __anon_1 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                    key: std::ptr::null_mut(),
                    value: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct xdp_md {
            pub data: u32,
            pub data_end: u32,
            pub data_meta: u32,
            pub ingress_ifindex: u32,
            pub rx_queue_index: u32,
            pub egress_ifindex: u32,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct udphdr {
            pub source: u16,
            pub dest: u16,
            pub len: u16,
            pub check: u16,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct rodata {}
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct maps {
            pub perf_map: __anon_1,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub _license: [i8; 4],
        }
    }
    pub struct OpenInterfaceTapSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenInterfaceTapMaps<'obj>,
        pub progs: OpenInterfaceTapProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenInterfaceTapSkel<'obj> {
        type Output = InterfaceTapSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<InterfaceTapSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(InterfaceTapSkel {
                maps: unsafe { InterfaceTapMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: InterfaceTapProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: InterfaceTapLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct InterfaceTapLinks {
        pub read_from_interface: Option<libbpf_rs::Link>,
    }
    pub struct InterfaceTapSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: InterfaceTapMaps<'obj>,
        pub progs: InterfaceTapProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: InterfaceTapLinks,
    }

    unsafe impl Send for InterfaceTapSkel<'_> {}
    unsafe impl Sync for InterfaceTapSkel<'_> {}

    impl<'obj> Skel<'obj> for InterfaceTapSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = InterfaceTapLinks {
                read_from_interface: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl InterfaceTapSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 176, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 10, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97,
        98, 0, 114, 97, 119, 95, 116, 114, 97, 99, 101, 112, 111, 105, 110, 116, 0, 46, 114, 111,
        100, 97, 116, 97, 0, 46, 109, 97, 112, 115, 0, 108, 105, 99, 101, 110, 115, 101, 0, 105,
        110, 116, 101, 114, 102, 97, 99, 101, 95, 116, 97, 112, 46, 98, 112, 102, 46, 99, 0, 76,
        66, 66, 48, 95, 54, 0, 76, 66, 66, 48, 95, 53, 0, 114, 101, 97, 100, 95, 102, 114, 111,
        109, 95, 105, 110, 116, 101, 114, 102, 97, 99, 101, 46, 95, 95, 95, 95, 102, 109, 116, 0,
        114, 101, 97, 100, 95, 102, 114, 111, 109, 95, 105, 110, 116, 101, 114, 102, 97, 99, 101,
        46, 95, 95, 95, 95, 102, 109, 116, 46, 49, 0, 114, 101, 97, 100, 95, 102, 114, 111, 109,
        95, 105, 110, 116, 101, 114, 102, 97, 99, 101, 0, 112, 101, 114, 102, 95, 109, 97, 112, 0,
        95, 108, 105, 99, 101, 110, 115, 101, 0, 46, 114, 101, 108, 114, 97, 119, 95, 116, 114, 97,
        99, 101, 112, 111, 105, 110, 116, 0, 46, 66, 84, 70, 0, 46, 66, 84, 70, 46, 101, 120, 116,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 54, 0, 0, 0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 74, 0, 0, 0, 0, 0, 3, 0, 32,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 81, 0, 0, 0, 0, 0, 3, 0, 200, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 88, 0, 0, 0, 1, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 42, 0, 0, 0,
        0, 0, 0, 0, 116, 0, 0, 0, 1, 0, 4, 0, 42, 0, 0, 0, 0, 0, 0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 146, 0, 0, 0, 18, 0,
        3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 1, 0, 0, 0, 0, 0, 0, 166, 0, 0, 0, 17, 0, 5, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 175, 0, 0, 0, 17, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        4, 0, 0, 0, 0, 0, 0, 0, 97, 18, 4, 0, 0, 0, 0, 0, 97, 20, 0, 0, 0, 0, 0, 0, 191, 67, 0, 0,
        0, 0, 0, 0, 7, 3, 0, 0, 196, 0, 0, 0, 45, 35, 31, 0, 0, 0, 0, 0, 191, 67, 0, 0, 0, 0, 0, 0,
        7, 3, 0, 0, 84, 2, 0, 0, 45, 35, 28, 0, 0, 0, 0, 0, 191, 69, 0, 0, 0, 0, 0, 0, 7, 5, 0, 0,
        148, 2, 0, 0, 45, 37, 25, 0, 0, 0, 0, 0, 105, 54, 4, 0, 0, 0, 0, 0, 220, 6, 0, 0, 16, 0, 0,
        0, 7, 6, 0, 0, 248, 255, 255, 255, 103, 6, 0, 0, 32, 0, 0, 0, 119, 6, 0, 0, 32, 0, 0, 0, 7,
        4, 0, 0, 92, 2, 0, 0, 191, 67, 0, 0, 0, 0, 0, 0, 15, 99, 0, 0, 0, 0, 0, 0, 61, 50, 5, 0, 0,
        0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 42, 0, 0, 0, 133,
        0, 0, 0, 6, 0, 0, 0, 5, 0, 11, 0, 0, 0, 0, 0, 24, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 24, 3, 0, 0, 255, 255, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 191, 101, 0, 0, 0, 0, 0, 0,
        133, 0, 0, 0, 121, 0, 0, 0, 24, 1, 0, 0, 42, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0,
        31, 0, 0, 0, 191, 99, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0, 0, 183, 0, 0, 0, 2, 0, 0, 0,
        149, 0, 0, 0, 0, 0, 0, 0, 117, 100, 112, 95, 104, 101, 97, 100, 101, 114, 95, 98, 121, 116,
        101, 115, 32, 116, 111, 111, 32, 102, 97, 114, 32, 112, 97, 115, 116, 32, 101, 110, 100,
        32, 111, 102, 32, 100, 97, 116, 97, 0, 67, 97, 112, 116, 117, 114, 101, 100, 32, 85, 68,
        80, 32, 104, 101, 97, 100, 101, 114, 32, 40, 37, 100, 32, 98, 121, 116, 101, 115, 41, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 71, 80, 76, 0, 0, 0, 0, 0, 160, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 7,
        0, 0, 0, 200, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 9, 0, 0, 0, 248, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 7, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 192, 2, 0, 0, 192, 2, 0, 0, 55,
        4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 17, 0, 0, 0, 5, 0, 0, 0, 0,
        0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 2, 9, 0, 0, 0, 25, 0, 0, 0, 0, 0, 0, 8, 10, 0, 0, 0, 31, 0, 0, 0, 0, 0,
        0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 32, 0, 0, 0, 44, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 49, 0, 0, 0, 5, 0, 0, 0, 64, 0, 0, 0, 61, 0, 0, 0, 7, 0, 0, 0, 128, 0, 0, 0,
        65, 0, 0, 0, 8, 0, 0, 0, 192, 0, 0, 0, 71, 0, 0, 0, 0, 0, 0, 14, 11, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 2, 14, 0, 0, 0, 80, 0, 0, 0, 6, 0, 0, 4, 24, 0, 0, 0, 87, 0, 0, 0, 9,
        0, 0, 0, 0, 0, 0, 0, 92, 0, 0, 0, 9, 0, 0, 0, 32, 0, 0, 0, 101, 0, 0, 0, 9, 0, 0, 0, 64, 0,
        0, 0, 111, 0, 0, 0, 9, 0, 0, 0, 96, 0, 0, 0, 127, 0, 0, 0, 9, 0, 0, 0, 128, 0, 0, 0, 142,
        0, 0, 0, 9, 0, 0, 0, 160, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 13, 2, 0, 0, 0, 157, 0, 0, 0, 13,
        0, 0, 0, 161, 0, 0, 0, 1, 0, 0, 12, 15, 0, 0, 0, 181, 0, 0, 0, 4, 0, 0, 4, 8, 0, 0, 0, 188,
        0, 0, 0, 18, 0, 0, 0, 0, 0, 0, 0, 195, 0, 0, 0, 18, 0, 0, 0, 16, 0, 0, 0, 200, 0, 0, 0, 18,
        0, 0, 0, 32, 0, 0, 0, 204, 0, 0, 0, 21, 0, 0, 0, 48, 0, 0, 0, 210, 0, 0, 0, 0, 0, 0, 8, 19,
        0, 0, 0, 217, 0, 0, 0, 0, 0, 0, 8, 20, 0, 0, 0, 223, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 16,
        0, 0, 0, 238, 0, 0, 0, 0, 0, 0, 8, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 23, 0, 0, 0, 246,
        0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 22, 0, 0,
        0, 4, 0, 0, 0, 42, 0, 0, 0, 251, 0, 0, 0, 0, 0, 0, 14, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 3, 0, 0, 0, 0, 22, 0, 0, 0, 4, 0, 0, 0, 31, 0, 0, 0, 23, 1, 0, 0, 0, 0, 0, 14, 26,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 23, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0,
        0, 53, 1, 0, 0, 0, 0, 0, 14, 28, 0, 0, 0, 1, 0, 0, 0, 18, 4, 0, 0, 2, 0, 0, 15, 73, 0, 0,
        0, 25, 0, 0, 0, 0, 0, 0, 0, 42, 0, 0, 0, 27, 0, 0, 0, 42, 0, 0, 0, 31, 0, 0, 0, 26, 4, 0,
        0, 1, 0, 0, 15, 32, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 32, 4, 0, 0, 1, 0, 0,
        15, 4, 0, 0, 0, 29, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 105, 110, 116, 0, 95, 95, 65, 82,
        82, 65, 89, 95, 83, 73, 90, 69, 95, 84, 89, 80, 69, 95, 95, 0, 95, 95, 117, 51, 50, 0, 117,
        110, 115, 105, 103, 110, 101, 100, 32, 105, 110, 116, 0, 116, 121, 112, 101, 0, 109, 97,
        120, 95, 101, 110, 116, 114, 105, 101, 115, 0, 107, 101, 121, 0, 118, 97, 108, 117, 101, 0,
        112, 101, 114, 102, 95, 109, 97, 112, 0, 120, 100, 112, 95, 109, 100, 0, 100, 97, 116, 97,
        0, 100, 97, 116, 97, 95, 101, 110, 100, 0, 100, 97, 116, 97, 95, 109, 101, 116, 97, 0, 105,
        110, 103, 114, 101, 115, 115, 95, 105, 102, 105, 110, 100, 101, 120, 0, 114, 120, 95, 113,
        117, 101, 117, 101, 95, 105, 110, 100, 101, 120, 0, 101, 103, 114, 101, 115, 115, 95, 105,
        102, 105, 110, 100, 101, 120, 0, 99, 116, 120, 0, 114, 101, 97, 100, 95, 102, 114, 111,
        109, 95, 105, 110, 116, 101, 114, 102, 97, 99, 101, 0, 117, 100, 112, 104, 100, 114, 0,
        115, 111, 117, 114, 99, 101, 0, 100, 101, 115, 116, 0, 108, 101, 110, 0, 99, 104, 101, 99,
        107, 0, 95, 95, 98, 101, 49, 54, 0, 95, 95, 117, 49, 54, 0, 117, 110, 115, 105, 103, 110,
        101, 100, 32, 115, 104, 111, 114, 116, 0, 95, 95, 115, 117, 109, 49, 54, 0, 99, 104, 97,
        114, 0, 114, 101, 97, 100, 95, 102, 114, 111, 109, 95, 105, 110, 116, 101, 114, 102, 97,
        99, 101, 46, 95, 95, 95, 95, 102, 109, 116, 0, 114, 101, 97, 100, 95, 102, 114, 111, 109,
        95, 105, 110, 116, 101, 114, 102, 97, 99, 101, 46, 95, 95, 95, 95, 102, 109, 116, 46, 49,
        0, 95, 108, 105, 99, 101, 110, 115, 101, 0, 47, 117, 115, 101, 114, 100, 97, 116, 97, 47,
        98, 112, 102, 47, 105, 110, 116, 101, 114, 102, 97, 99, 101, 95, 116, 97, 112, 47, 115,
        114, 99, 47, 98, 112, 102, 47, 105, 110, 116, 101, 114, 102, 97, 99, 101, 95, 116, 97, 112,
        46, 98, 112, 102, 46, 99, 0, 32, 32, 118, 111, 105, 100, 32, 42, 100, 97, 116, 97, 95, 101,
        110, 100, 32, 61, 32, 40, 118, 111, 105, 100, 32, 42, 41, 40, 108, 111, 110, 103, 41, 99,
        116, 120, 45, 62, 100, 97, 116, 97, 95, 101, 110, 100, 59, 0, 32, 32, 118, 111, 105, 100,
        32, 42, 100, 97, 116, 97, 32, 61, 32, 40, 118, 111, 105, 100, 32, 42, 41, 40, 108, 111,
        110, 103, 41, 99, 116, 120, 45, 62, 100, 97, 116, 97, 59, 0, 32, 32, 105, 102, 32, 40, 40,
        118, 111, 105, 100, 32, 42, 41, 40, 101, 116, 104, 32, 43, 32, 115, 105, 122, 101, 111,
        102, 40, 115, 116, 114, 117, 99, 116, 32, 101, 116, 104, 104, 100, 114, 41, 41, 32, 62, 32,
        100, 97, 116, 97, 95, 101, 110, 100, 41, 32, 123, 0, 32, 32, 105, 102, 32, 40, 40, 118,
        111, 105, 100, 32, 42, 41, 40, 105, 112, 32, 43, 32, 115, 105, 122, 101, 111, 102, 40, 115,
        116, 114, 117, 99, 116, 32, 105, 112, 104, 100, 114, 41, 41, 32, 62, 32, 100, 97, 116, 97,
        95, 101, 110, 100, 41, 32, 123, 0, 32, 32, 105, 102, 32, 40, 40, 118, 111, 105, 100, 32,
        42, 41, 40, 117, 100, 112, 32, 43, 32, 115, 105, 122, 101, 111, 102, 40, 115, 116, 114,
        117, 99, 116, 32, 117, 100, 112, 104, 100, 114, 41, 41, 32, 62, 32, 100, 97, 116, 97, 95,
        101, 110, 100, 41, 32, 123, 0, 32, 32, 117, 110, 115, 105, 103, 110, 101, 100, 32, 105,
        110, 116, 32, 112, 97, 121, 108, 111, 97, 100, 95, 108, 101, 110, 32, 61, 32, 98, 112, 102,
        95, 110, 116, 111, 104, 115, 40, 117, 100, 112, 45, 62, 108, 101, 110, 41, 32, 45, 32, 115,
        105, 122, 101, 111, 102, 40, 115, 116, 114, 117, 99, 116, 32, 117, 100, 112, 104, 100, 114,
        41, 59, 0, 32, 32, 105, 102, 32, 40, 40, 118, 111, 105, 100, 32, 42, 41, 112, 97, 121, 108,
        111, 97, 100, 32, 43, 32, 112, 97, 121, 108, 111, 97, 100, 95, 108, 101, 110, 32, 62, 32,
        100, 97, 116, 97, 95, 101, 110, 100, 41, 32, 123, 0, 32, 32, 117, 110, 115, 105, 103, 110,
        101, 100, 32, 99, 104, 97, 114, 32, 42, 112, 97, 121, 108, 111, 97, 100, 32, 61, 32, 40,
        117, 110, 115, 105, 103, 110, 101, 100, 32, 99, 104, 97, 114, 32, 42, 41, 117, 100, 112,
        32, 43, 32, 115, 105, 122, 101, 111, 102, 40, 115, 116, 114, 117, 99, 116, 32, 117, 100,
        112, 104, 100, 114, 41, 59, 0, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116,
        107, 40, 34, 117, 100, 112, 95, 104, 101, 97, 100, 101, 114, 95, 98, 121, 116, 101, 115,
        32, 116, 111, 111, 32, 102, 97, 114, 32, 112, 97, 115, 116, 32, 101, 110, 100, 32, 111,
        102, 32, 100, 97, 116, 97, 34, 41, 59, 0, 32, 32, 98, 112, 102, 95, 120, 100, 112, 95, 111,
        117, 116, 112, 117, 116, 40, 99, 116, 120, 44, 32, 38, 112, 101, 114, 102, 95, 109, 97,
        112, 44, 32, 66, 80, 70, 95, 70, 95, 67, 85, 82, 82, 69, 78, 84, 95, 67, 80, 85, 44, 32,
        112, 97, 121, 108, 111, 97, 100, 44, 32, 112, 97, 121, 108, 111, 97, 100, 95, 108, 101,
        110, 41, 59, 0, 32, 32, 98, 112, 102, 95, 112, 114, 105, 110, 116, 107, 40, 34, 67, 97,
        112, 116, 117, 114, 101, 100, 32, 85, 68, 80, 32, 104, 101, 97, 100, 101, 114, 32, 40, 37,
        100, 32, 98, 121, 116, 101, 115, 41, 34, 44, 32, 112, 97, 121, 108, 111, 97, 100, 95, 108,
        101, 110, 41, 59, 0, 125, 0, 48, 58, 49, 0, 48, 58, 48, 0, 48, 58, 50, 0, 46, 114, 111,
        100, 97, 116, 97, 0, 46, 109, 97, 112, 115, 0, 108, 105, 99, 101, 110, 115, 101, 0, 114,
        97, 119, 95, 116, 114, 97, 99, 101, 112, 111, 105, 110, 116, 0, 0, 159, 235, 1, 0, 32, 0,
        0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 20, 0, 0, 0, 44, 1, 0, 0, 64, 1, 0, 0, 60, 0, 0, 0, 8, 0, 0,
        0, 40, 4, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 16, 0, 0, 0, 40, 4, 0, 0, 18, 0, 0, 0,
        0, 0, 0, 0, 62, 1, 0, 0, 118, 1, 0, 0, 39, 72, 0, 0, 8, 0, 0, 0, 62, 1, 0, 0, 166, 1, 0, 0,
        35, 68, 0, 0, 16, 0, 0, 0, 62, 1, 0, 0, 206, 1, 0, 0, 20, 88, 0, 0, 32, 0, 0, 0, 62, 1, 0,
        0, 206, 1, 0, 0, 7, 88, 0, 0, 40, 0, 0, 0, 62, 1, 0, 0, 8, 2, 0, 0, 19, 128, 0, 0, 56, 0,
        0, 0, 62, 1, 0, 0, 8, 2, 0, 0, 7, 128, 0, 0, 64, 0, 0, 0, 62, 1, 0, 0, 64, 2, 0, 0, 20,
        168, 0, 0, 80, 0, 0, 0, 62, 1, 0, 0, 64, 2, 0, 0, 7, 168, 0, 0, 88, 0, 0, 0, 62, 1, 0, 0,
        122, 2, 0, 0, 30, 184, 0, 0, 104, 0, 0, 0, 62, 1, 0, 0, 122, 2, 0, 0, 50, 184, 0, 0, 112,
        0, 0, 0, 62, 1, 0, 0, 196, 2, 0, 0, 23, 196, 0, 0, 128, 0, 0, 0, 62, 1, 0, 0, 246, 2, 0, 0,
        49, 188, 0, 0, 136, 0, 0, 0, 62, 1, 0, 0, 196, 2, 0, 0, 23, 196, 0, 0, 152, 0, 0, 0, 62, 1,
        0, 0, 196, 2, 0, 0, 7, 196, 0, 0, 160, 0, 0, 0, 62, 1, 0, 0, 63, 3, 0, 0, 5, 200, 0, 0,
        200, 0, 0, 0, 62, 1, 0, 0, 124, 3, 0, 0, 3, 216, 0, 0, 248, 0, 0, 0, 62, 1, 0, 0, 199, 3,
        0, 0, 3, 224, 0, 0, 32, 1, 0, 0, 62, 1, 0, 0, 4, 4, 0, 0, 1, 236, 0, 0, 16, 0, 0, 0, 40, 4,
        0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 6, 4, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 14, 0, 0, 0,
        10, 4, 0, 0, 0, 0, 0, 0, 88, 0, 0, 0, 17, 0, 0, 0, 14, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0,
        0, 0, 0, 0, 0, 217, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 32, 1, 0, 0, 0, 0, 0, 0, 8, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0,
        0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 40, 2, 0, 0, 0, 0, 0, 0, 48, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 88, 3, 0, 0, 0, 0, 0, 0, 73, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 168, 3, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 46, 0, 0, 0, 1, 0,
        0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 200, 3, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 184, 0,
        0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 208, 3, 0, 0, 0, 0, 0,
        0, 48, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0,
        0, 0, 0, 203, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0,
        0, 0, 0, 0, 0, 15, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 208, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 16, 11, 0, 0, 0, 0, 0, 0, 156, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
